### ISSUE TITLE
Co-Location of Tests

### ISSUE THREAD

**Issue by kitsonk** [kitsonk/dojo2-boilerplate-package#1]
@neonstalwart suggested we shouldn't require all tests to be co-located in a single path, and if a developer so desires can co-locate the tests with the module code.

I see several disadvantages to this:
- Makes it difficult to consume tests and then automate their testing with a toolchain
- Makes it difficult to exclude tests from a build process or a deployment to a production enviornment.

So I stand by the co-location of tests.

**Comment by neonstalwart** [comment]
i did not suggest that we require it - i suggested it should be allowed.

i disagree with both your points since it's already possible to achieve both today based on dojo's build tool.
