### ISSUE TITLE
Usage of JSDoc versus dojodoc

### ISSUE THREAD

**Issue by kitsonk** [kitsonk/dojo2-boilerplate-package#6]
@csnover has suggested that we adopt JSDoc versus using dojodoc for Dojo 2.  I agree with him in the sense that dojodoc leaves us out on our own, while JSDoc is a slightly more common way of inlining documentation.

**Comment by phated** [comment]
I agree with using a more common/standard form of inline docs.  JSDoc is what we are using for FrozenJS - the current downside is that it depends on Java still, but I did an initial implementation of https://github.com/jdalton/docdown in JS https://github.com/phated/docdown/tree/js

**Comment by monteslu** [comment]
Another +1 for jsdoc.  Might as well go with the flow unless there's a compelling feature that jsdoc is missing.
Also we get the benefit of other tooling such as the jsdoc plugin for sublime.

**Comment by gaurav21r** [comment]
+1 for jsDoc! We have Dojo as the standard toolkit for all our web / mobile development. We also use it in PHP projects. jsDoc follows the same doclet structure like JavaDoc and PHPDoc and is already quite actively used by the community. This move will only enable more people in the community to "feel at home" when it comes to Dojo. 

Though, [Dojo's API UI](http://dojotoolkit.org/api/) is by far the best I've ever seen. A close second being [Google's Closure Library API](http://docs.closure-library.googlecode.com/git/class_goog_ui_DatePicker.html) which by  the way uses jsDoc. We don't have to get rid of the UI. As it is being generated from an XML output, we can use the steps highlighted [here](https://groups.google.com/forum/?fromgroups#!topic/jsdoc-users/1mxZrr9kq7U) for generating the same UI for Dojo Docs.

Also, Dojo's build system uses Closure Compiler as one of the build engines. This great Compiler from Google actually uses [jsDoc annotations](https://developers.google.com/closure/compiler/docs/js-for-compiler) to check code.

Dojo should definitely move to jsDoc as the documentation standard. I am sure the community (including our organisation) is more than willing to help with the transition process. It will lead to wider adoption and greater community support.
